// <auto-generated />
namespace WorkflowENG.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FirstAndStart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstAndStart));
        
        string IMigrationMetadata.Id
        {
            get { return "202010110552542_FirstAndStart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
